
# Modelos de pronóstico: revisión con clima actualizado

Todos los modelos semanales aprendidos de esta tabla son variantes de HistGradientBoostingRegressor (árboles de decisión). La validación anterior a 2026 selecciona Boosting sin clima; no se cambia por el resultado de test.

La configuración semanal seleccionada no utiliza variables meteorológicas. El componente diario conserva temperatura, humedad y radiación en sus pesos; son etapas distintas.

## Semanales: mismos 15.838 casos principales de 2026

| Método | Casos | MAE (tallos) | WAPE | Sesgo |
| --- | ---: | ---: | ---: | ---: |
| Memoria larga antes de actualizar clima | 15.838 | 2.512,65 | 19,59 % | -3,54 % |
| Boosting con clima ampliado y lluvia | 15.838 | 2.496,43 | 19,46 % | -2,96 % |
| Boosting con clima básico actualizado | 15.838 | 2.510,25 | 19,57 % | -3,58 % |
| Clima ampliado + curva atribuida a GAITANA | 15.838 | 2.515,81 | 19,61 % | -2,76 % |
| Boosting sin clima | 15.838 | 2.496,17 | 19,46 % | -2,42 % |
| Ingeniero | 15.838 | 2.531,72 | 19,74 % | -9,75 % |

| Horizonte | Casos | WAPE anterior | WAPE actual | WAPE ingeniero | Ventaja actual vs. ingeniero (pp) |
| --- | ---: | ---: | ---: | ---: | ---: |
| H1 | 3.413 | 15,68 % | 15,66 % | 17,09 % | 1,43 |
| H2 | 3.289 | 17,56 % | 17,37 % | 19,28 % | 1,91 |
| H3 | 3.166 | 20,39 % | 20,39 % | 20,32 % | -0,07 |
| H4 | 3.045 | 22,14 % | 21,96 % | 20,91 % | -1,04 |
| H5 | 2.925 | 22,77 % | 22,50 % | 21,40 % | -1,10 |
| Conjunto | 15.838 | 19,59 % | 19,46 % | 19,74 % | 0,28 |

| Horizonte | Sesgo anterior | Sesgo actual | Sesgo ingeniero |
| --- | ---: | ---: | ---: |
| H1 | -1,71 % | -1,23 % | -7,56 % |
| H2 | -3,41 % | -2,40 % | -8,17 % |
| H3 | -3,89 % | -2,70 % | -9,46 % |
| H4 | -4,63 % | -3,27 % | -11,32 % |
| H5 | -4,23 % | -2,63 % | -12,63 % |
| Conjunto | -3,54 % | -2,42 % | -9,75 % |

Sesgo = 100 × suma(predicción − real) / suma(real). Positivo: sobreestimación; negativo: subestimación. Cero no implica poco error: errores opuestos pueden compensarse. WAPE y sesgo se calculan sobre los mismos casos por horizonte.

## H1 por separado

Mismos **3.413 casos**. H1 es la primera semana pronosticada desde el lunes de emisión.

| H1: método | WAPE | MAE (tallos) | Sesgo medio (tallos) | Sesgo (%) |
| --- | ---: | ---: | ---: | ---: |
| Anterior | 15,68 % | 1.980,53 | -216,37 | -1,71 % |
| Actual: boosting sin clima | 15,66 % | 1.978,16 | -155,84 | -1,23 % |
| Ingeniero | 17,09 % | 2.158,89 | -955,34 | -7,56 % |

Frente al ingeniero, el WAPE baja **1,43 puntos**, equivalente a **8,37 % menos error absoluto** en estos casos. El sesgo negativo indica subestimación; cuanto más cerca de cero, menor desvío del volumen total.

## Diarios: mismos días observados

(En revisión: desarrollo preliminar y siguientes pasos.)

| Método | Casos | MAE (tallos) | WAPE | Sesgo |
| --- | ---: | ---: | ---: | ---: |
| Diario autónomo antes de actualizar clima | 22.973 | 543,76 | 26,76 % | -7,23 % |
| Boosting reconciliado · selección semanal | 22.973 | 554,07 | 27,27 % | -5,91 % |
| Boosting diario autónomo | 22.973 | 542,84 | 26,72 % | -7,11 % |
| Boosting reconciliado · memoria actualizada | 22.973 | 557,45 | 27,44 % | -6,21 % |
| Perfil histórico · selección semanal | 22.973 | 562,66 | 27,69 % | -5,48 % |
| Perfil histórico · memoria actualizada | 22.973 | 565,88 | 27,85 % | -5,78 % |
| Diario reconciliado antes de actualizar clima | 22.973 | 557,78 | 27,45 % | -6,21 % |
| Uniforme · selección semanal | 22.973 | 584,97 | 28,79 % | -16,81 % |
| Uniforme · memoria actualizada | 22.973 | 589,48 | 29,01 % | -17,03 % |

El autónomo no está obligado a sumar al total semanal. Los repartos sí. SARIMA/SARIMAX se evalúan sólo en tres series y no se mezclan con esta población; consultar el piloto en diario 05. El EDA no demuestra una regla causal de retraso por clima. Para train/test del mismo ajuste consultar 19, diario 05 y el inventario 17.

## Qué mejoró

- Semanal conjunto: WAPE **19,59 % → 19,46 %**; ingeniero **19,74 %**. Sesgo **-3,54 % → -2,42 %**; ingeniero **-9,75 %**.
- El modelo supera al ingeniero en WAPE en **H1 y H2**; el ingeniero conserva menor WAPE en **H3–H5**. El modelo tiene menor sesgo absoluto en los cinco horizontes.
- Diario reconciliado: **27,45 % → 27,27 %**. Diario autónomo: **26,76 % → 26,72 %**. La mejora es pequeña y el autónomo sigue teniendo menor WAPE.
- La ventaja semanal conjunta frente al ingeniero es 0,28 puntos, con intervalo exploratorio de 95 % [-1,27; 1,72]. Incluye cero: el resultado retrospectivo es favorable, pero no demuestra superioridad estable.

La lluvia y las ventanas ampliadas mejoran frente al clima básico en el test. Sin clima y clima ampliado quedan prácticamente empatados (19,458 % y 19,460); se conserva el candidato elegido en la validación. Restringir las curvas a pilotos atribuibles a GAITANA pierde cobertura y empeora el WAPE respecto a la curva compartida con el mismo clima ampliado; se conserva la referencia compartida. Esto no prueba ausencia de efecto agronómico del clima.

## De dónde viene el error

[Notebook 20](Notebooks/Analisis/20_EDA_origen_error_modelo_ingeniero.ipynb): conserva las predicciones y descompone los mismos casos. «Error del modelo (%)» es su participación en el error absoluto; el aporte se expresa en puntos del WAPE total.

### H1: cuatro productos principales

| Producto | Volumen (%) | WAPE modelo | WAPE ingeniero | Error del modelo (%) | Aporte WAPE (pp) |
| --- | ---: | ---: | ---: | ---: | ---: |
| MINICARNATION | 60,34 | 14,33 % | 14,53 % | 55,23 | 8,65 |
| CARNATION | 18,52 | 18,91 % | 20,17 % | 22,36 | 3,50 |
| SOLOMIO | 11,34 | 15,17 % | 18,77 % | 10,99 | 1,72 |
| RAFFINE | 6,04 | 15,96 % | 25,58 % | 6,15 | 0,96 |

### H1–H5: cuatro productos principales

| Producto | Volumen (%) | WAPE modelo | WAPE ingeniero | Error del modelo (%) | Aporte WAPE (pp) |
| --- | ---: | ---: | ---: | ---: | ---: |
| MINICARNATION | 60,78 | 17,67 % | 17,75 % | 55,19 | 10,74 |
| CARNATION | 18,31 | 23,40 % | 22,43 % | 22,02 | 4,28 |
| SOLOMIO | 11,22 | 18,20 % | 18,54 % | 10,49 | 2,04 |
| RAFFINE | 6,03 | 22,99 % | 29,36 % | 7,12 | 1,39 |

- **Concentración:** MINICARNATION y CARNATION suman 77,59 % del error H1 del modelo. MINICARNATION domina también el del ingeniero (51,31 %), principalmente por volumen.
- **De dónde ganamos:** RAFFINE y SOLOMIO explican aproximadamente 69,11 % de la ventaja neta H1. En MINICARNATION ganamos sólo 3/8 meses, pese a la pequeña ventaja acumulada. En H5, CARNATION aporta 0,67 puntos a nuestra desventaja.
- **Colores:** ORANGE, HOT PINK y LIGHT PINK de MINICARNATION concentran el mayor error H1 de ambos métodos. Se comparan dentro de producto, sin mezclar identidades.
- **Variedades:** UCHUVA es la de mayor error de ambos; le siguen LORENZO y ACADEMY en el modelo, LORENZO y NENUFAR en el ingeniero. La mayor desventaja del modelo es EPSILON: WAPE 15,17 % frente a 10,11 %.
- **Sesgo no es precisión:** ACADEMY tiene sesgo 0,19 %, pero WAPE 19,15 %. En H1, sobreestimaciones (7,21 pp) y subestimaciones (8,45 pp) se compensan en el sesgo, pero se suman en WAPE.
- **Explicación a revisar:** el modelo queda corto en subidas fuertes, pero 89,39 % de su error ocurre en casos sin cambios extremos respecto a media4. Variabilidad previa, seguimiento de picos y cobertura merecen revisión; no son causas demostradas. El notebook incluye semanas y trayectorias de UCHUVA, EPSILON y ACADEMY. No se modificaron modelos mirando este test.


# Guía vigente: clima, proyecciones y pronóstico de GAITANA

## Qué leer primero

El [trabajo escrito](Trabajo%20escrito/Estructura_actualizada_con_resultados.docx) y su [Markdown editable](Trabajo%20escrito/Desarrollo_del_documento.md) conservan resultados y desarrollan ahora el recorrido metodológico. Para entender, leer en este orden:

1. **Antes del modelo:** capítulos 2–3, fuentes, homologación comercial, tallos por planta, curvas y cobertura. Distinguir cero de dato ausente.
2. **Qué es una fila:** 4.1, anexo de 47 columnas y [lectura.ipynb](lectura.ipynb). Separar origen, objetivo y versiones previas.
3. **Por qué esas variables:** 3.6.1 y 3.7; asociaciones de 11, tendencias de diario 01 y puente climático de 18. Una asociación propone una hipótesis; no demuestra mejora predictiva.
4. **Qué hace cada modelo:** 4.2 y diccionario del notebook 12; referencias → correcciones Ridge/boosting → dos rutas → información diaria para semanas → grupos de horizonte y memoria larga → comparación climática de 19.
5. **Qué evidencia respalda las decisiones:** recorrido de resultados del capítulo 5, selección temporal, benchmark, WAPE y sesgo, y errores por producto/color/variedad en 5.6 y notebook 20.
6. **Pasos siguientes:** capítulo 7. Pronóstico diario y SARIMA/SARIMAX se conservan como desarrollo preliminar en revisión; no son un requisito para entender primero el sistema semanal.

La [bitácora](BITACORA_REVISION_CONVERSADA.md) registra decisiones, límites y el esquema de presentación en cuatro bloques. El orden de lectura anterior explica la metodología; el orden de corrida de abajo respeta dependencias de archivos.

## Resultado actual

Clima válido de GAITANA hasta **21 de septiembre de 2026**. Sólo se modela GAITANA: no se amplía el benchmark ni las conclusiones a ARABELLA. La lluvia se incorpora en unidades de fuente, con cobertura explícita. Los intervalos del EDA de desplazamiento incluyen cero: no se demuestra una regla general de retraso/adelanto por clima.

Elección fijada con validación anterior a 2026: **Boosting sin clima**. WAPE conjunto 19,46 %, ingeniero 19,74 %, mismos 15.838 casos. Una ventaja positiva de WAPE favorece al modelo; el sesgo tiene signo propio:

| Horizonte | Casos | WAPE anterior | WAPE actual | WAPE ingeniero | Ventaja actual vs. ingeniero (pp) |
| --- | ---: | ---: | ---: | ---: | ---: |
| H1 | 3.413 | 15,68 % | 15,66 % | 17,09 % | 1,43 |
| H2 | 3.289 | 17,56 % | 17,37 % | 19,28 % | 1,91 |
| H3 | 3.166 | 20,39 % | 20,39 % | 20,32 % | -0,07 |
| H4 | 3.045 | 22,14 % | 21,96 % | 20,91 % | -1,04 |
| H5 | 2.925 | 22,77 % | 22,50 % | 21,40 % | -1,10 |
| Conjunto | 15.838 | 19,59 % | 19,46 % | 19,74 % | 0,28 |

| Horizonte | Sesgo anterior | Sesgo actual | Sesgo ingeniero |
| --- | ---: | ---: | ---: |
| H1 | -1,71 % | -1,23 % | -7,56 % |
| H2 | -3,41 % | -2,40 % | -8,17 % |
| H3 | -3,89 % | -2,70 % | -9,46 % |
| H4 | -4,63 % | -3,27 % | -11,32 % |
| H5 | -4,23 % | -2,63 % | -12,63 % |
| Conjunto | -3,54 % | -2,42 % | -9,75 % |

Sesgo = 100 × suma(predicción − real) / suma(real). Positivo: sobreestimación; negativo: subestimación. Cero no implica poco error: errores opuestos pueden compensarse. WAPE y sesgo se calculan sobre los mismos casos por horizonte.

(Pronóstico diario en revisión: desarrollo preliminar y siguientes pasos.) Diario reconciliado al candidato: **27,27 %**; autónomo: **26,72 %**, mismos 22.973 días. No confundir precisión libre con conservar el total semanal. Leer sensibilidad de semanas con siete reportes, que no puede usarse para escoger método al origen.

## Lo que sabemos de las curvas

La auditoría inicial recuperó 74.304 observaciones utilizables en la edición 2026; la teoría completa global pasó de 17,96 % a 21,25 %. No sumar recuperaciones entre ediciones que repiten historia. El catálogo comercial central conserva IDs y ambigüedades; 33 combinaciones con obtentor discrepante siguen pendientes de revisión agronómica.

La atribución por bloque+cama+variedad+fecha de siembra identifica 241.564 observaciones de 2026 como GAITANA y deja 202.912 sin pareja. No se encontró atribución inequívoca a ARABELLA. No afirmar que la curva original mezclaba comprobablemente fincas. Al restringir a pilotos atribuibles, la cobertura de plantas de GAITANA pasa de 79,12 % a 74,78 %: son exposiciones por plano/horizonte, no plantas físicas únicas ni cobertura del panel de casos. El experimento 19 compara la alternativa sin inventar curvas ni ocultar el cambio al respaldo.

## Orden exacto de corrida

Usar el intérprete `entorno_tesis`. Abrir cada notebook, reiniciar su kernel y ejecutar todas sus celdas de arriba abajo; esperar a que termine sin errores antes del siguiente. Las dependencias son archivos explícitos, no variables de otro kernel. Las bases limpias locales de producción y estimados deben existir; no hace falta consultar SQL de nuevo para esta actualización climática.

1. [Limpieza clima](Notebooks/Limpieza%20data,%20Notebooks%20y%20Scripts/02_limpieza_clima.ipynb): Actualizar fuente climática y verificar fechas/conflictos.
2. [Catálogo](Notebooks/Proyecciones%20Teoricas%20Propias/00_catalogo_variedades.ipynb): Reglas comunes de variedad.
3. [Auditoría](Notebooks/Proyecciones%20Teoricas%20Propias/Auditoria_calidad_curvas.ipynb): Recuperación y conservación.
4. [Proyecciones](Notebooks/Proyecciones%20Teoricas%20Propias/Proyecciones_teoricas_todos_los_anios.ipynb): Recuperar proyecciones compartidas auditadas.
5. [Procedencia](Notebooks/Proyecciones%20Teoricas%20Propias/01_procedencia_pilotos_y_curvas_gaitana.ipynb): Probar curva atribuible a GAITANA.
6. [Base semanal](Notebooks/Analisis/10_base_analitica_proyecciones.ipynb): Integración de producción, teoría y clima.
7. [EDA general](Notebooks/Analisis/11_EDA_proyecciones.ipynb): Composición y señales históricas.
8. [Modelos iniciales](Notebooks/Analisis/12_modelo_ajuste_proyecciones.ipynb): Referencias, Ridge y boosting.
9. [Benchmark](Notebooks/Analisis/13_comparacion_ingeniero_modelo_2026.ipynb): Mismos casos del ingeniero.
10. [Base diaria](Notebooks/Modelo_de_series_diario/01_base_diaria_EDA.ipynb): Calendario y señales conocidas al origen. Este paso construye entradas del SEMANAL; no exige entrenar pronósticos diarios.
11. [Tendencias](Notebooks/Analisis/14_tendencias_diarias_modelo_semanal.ipynb): Señales diarias en el pronóstico semanal.
12. [Memoria](Notebooks/Analisis/15_calidad_y_mejora_por_horizonte.ipynb): Arquitectura de referencia con memoria larga.
13. [EDA climático](Notebooks/Analisis/18_EDA_clima_y_desfase.ipynb): Relacionar las 26 variables climáticas originales/diarias/ampliadas con los modelos; cobertura, error y desplazamiento. Requiere base semanal y señales de diario 01.
14. [Comparación climática](Notebooks/Analisis/19_modelos_clima_y_curvas_gaitana.ipynb): Ablaciones y selección pre2026.
15. [Interpretación](Notebooks/Analisis/16_interpretacion_modelo_semanal.ipynb): Importancia del candidato seleccionado.
16. [EDA del origen del error](Notebooks/Analisis/20_EDA_origen_error_modelo_ingeniero.ipynb): Producto → color → variedad; H1 y H1–H5, aportes al WAPE, sesgo y semanas críticas. Usa salidas de 10 y 19; no reentrena.
17. [Distribución diaria](Notebooks/Modelo_de_series_diario/02_distribucion_semanal_a_diaria.ipynb): Autónomo y pesos de reparto. **(En revisión: desarrollo preliminar y siguientes pasos.)**
18. [Piloto temporal](Notebooks/Modelo_de_series_diario/03_SARIMA_SARIMAX_y_boosting.ipynb): Tres series, convergencia y clima lag7. **(En revisión: desarrollo preliminar y siguientes pasos.)**
19. [Reparto con memoria](Notebooks/Modelo_de_series_diario/04_diario_con_memoria_semanal.ipynb): Referencia actualizada. **(En revisión: desarrollo preliminar y siguientes pasos.)**
20. [Inventario train/test](Notebooks/Analisis/17_inventario_modelos_train_test.ipynb): Errores por corte y componentes train del diario.
21. [Diario vigente](Notebooks/Modelo_de_series_diario/05_diario_clima_actualizado.ipynb): Propagar selección y medir train/test compuesto. **(En revisión: desarrollo preliminar y siguientes pasos.)**

En proyecciones de todos los años, `RECALCULAR_DESDE_EXCEL=False` recupera la auditoría vigente. Si cambian fuentes de planos/pilotos: catálogo → todos los años con `True` → auditoría → todos los años con `False` → procedencia y resto de la cadena. Conservar referencias históricas de calidad y clima: no sustituir el “antes” por el resultado actualizado.

Para sólo estudiar no hace falta reentrenar. Para reproducir solo la extensión semanal con entradas ya actualizadas: procedencia → 18 → 19 → 16 → 20. Para estudiar o ejecutar el diario en revisión, continuar por diario 02/03/04 → 17 → diario 05 según las dependencias existentes. Los resultados de 10, diario 01, 14, 15 y diario 02/03/04 deben corresponder al mismo clima vigente; no mezclar archivos de revisiones anteriores.

## Cómo se evalúa

No hay división aleatoria. Cada ajuste mensual entrena sólo con semanas objetivo terminadas antes del primer origen de ese mes. Los pesos/preparación se ajustan en train y los predictores usan datos anteriores al lunes. El notebook 12 usa tres cortes (2025-07-07, 2026-01-05 y 2026-05-04), con ocho semanas de orígenes por evaluación; 13–19 pasan al reentrenamiento mensual. El experimento 19 selecciona entre cuatro alternativas con noviembre–diciembre de 2025, objetivos cerrados antes de 2026, y mantiene esa elección durante la evaluación. Todo el proyecto sigue siendo desarrollo retrospectivo porque esos periodos ya se examinaron.

Las tablas train/test de 19 y diario 05 corresponden al mismo corte. El test principal semanal usa el emparejamiento estricto del ingeniero; `test` sin sufijo en los controles de 19 incluye todos los casos elegibles, mientras `test_principal` conserva sólo la comparación estricta. No restar train del último ajuste al test acumulado de todo el año como si fueran la misma población. El inventario 17 mantiene referencias iniciales con sus propios periodos.

## Archivos de resultados

- `Datos_analiticos_proyecto/revision_clima_finca/auditoria_finca_curvas.xlsx`: atribuciones, ambigüedades y cobertura.
- `eda_clima_y_desfase.xlsx`, en esa carpeta: cobertura, asociaciones dentro de serie, ventanas sin superposición e incertidumbre.
- `eda_clima_variables_modelos.xlsx`: las 26 columnas climáticas, soporte por variable y común, correlaciones por serie/horizonte; figura `clima_variables_modelos.png` en el escrito.
- `resultados_clima_curvas.xlsx`: validación, modelos, horizontes, movimiento del estimado, rutas y train/test por corte.
- `Datos_analiticos_proyecto/modelo_diario/resultados_diarios_clima.xlsx`: precisión diaria, siete reportes, panel estricto, piloto y train/test compuesto.
- `Datos_analiticos_proyecto/modelo_con_proyecciones_teoricas/interpretacion_modelo_semanal.xlsx`: importancia por permutación del candidato. No es SHAP ni causalidad.
- [Resumen de modelos](resumen_modelos_pronostico.md): tablas separadas semanal y diaria, con nombres comprensibles.

## Actualizar el Word

Tras ejecutar y revisar cifras e interpretación en `Trabajo escrito/Desarrollo_del_documento.md`, correr desde la raíz:

```powershell
.\entorno_tesis\Scripts\python.exe "Trabajo escrito/actualizar_word.py"
```

El script genera el Word desde el Markdown y las figuras; no reentrena ni reescribe automáticamente conclusiones. No subir datasets. Las fuentes originales permanecen intactas. Los notebooks antiguos del benchmark se conservan como evidencia, no constituyen otro recorrido obligatorio.

## Pendientes concretos

Confirmar unidades de lluvia, microclima representado por la estación, latencia de reportes y finca de pilotos sin pareja. Aclarar días sin reporte antes de interpretarlos como ausencia de corte. Validar el candidato en nuevas fechas con emisiones archivadas y configuración fijada. Mantener GAITANA PPTO separada y no afirmar equivalencia exportable ni ahorros empresariales sin evidencia.

## Estudiar el origen del error

En 20 empezar por aportes por producto y después por color/variedad. Separar WAPE local, participación en el error y aporte al WAPE total. Leer las sobre/subestimaciones antes de concluir por sesgo. Revisar estabilidad mensual, curvas disponibles y variabilidad previa; los cambios del real frente a media4 son diagnóstico ex post, no predictores.

Las salidas están en `Datos_analiticos_proyecto/eda_origen_error/`: Excel con todos los grupos, horizontes y casos; Parquet de casos comparables; Markdown de hallazgos calculados. El foco de tres variedades es exploratorio, elegido mirando test. No modifica ni mejora artificialmente las predicciones. Para reproducir sólo este EDA, ejecutar 20 con las salidas vigentes de 10 y 19. Si cambian esas fuentes, revisar la interpretación escrita tras ejecutar y regenerar el Word. Mantener el Word cerrado al guardarlo.

## Próximos experimentos, todavía sin ejecutar

Comparar cinco ajustes H1–H5 frente a los dos grupos actuales; especialización por producto y prueba n−1 retirando un producto del entrenamiento pero evaluando los productos restantes sobre los mismos casos; verificar si edades tempranas de DINO sin soporte corresponden a ceros documentados. Fijar decisiones en validación y comprobarlas en un período nuevo, sin prometer reducción de WAPE. El pronóstico diario requiere profundizar calendario, cobertura y ajuste de parámetros; sus resultados se conservan como avance.


## Cargar la base analítica consolidada

Base semanal común generada en el notebook 10: proyecciones, producción real, rezagos y clima. Las etapas posteriores añaden las variables diarias y de memoria específicas de cada modelo.

In [1]:
from pathlib import Path
import pandas as pd

raiz = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "Datos_analiticos_proyecto").is_dir())
ruta = raiz / "Datos_analiticos_proyecto/modelo_con_proyecciones_teoricas/base_analitica_proyecciones.parquet"
base_analitica = pd.read_parquet(ruta)

print(f"{base_analitica.shape[0]:,} filas y {base_analitica.shape[1]} columnas")
base_analitica.head()


621,195 filas y 47 columnas


,finca,producto,color,variedad,origen,produccion_lag1,produccion_lag2,produccion_lag3,media_4,media_8,...,cohortes,teoria_previa_1,teoria_previa_2,revision_teoria,curva_completa,antiguedad_curva,teoria_modelo,desviacion_reciente_teoria,admisible_modelo,motivo_cobertura
0,GAITANA,ACHILLEA,LIGHT PINK,SASSY SUMMER TAFFY,2023-07-24,60.0,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,False,3.0,NaN,NaN,False,cohortes_sin_curva
1,GAITANA,ACHILLEA,LIGHT PINK,SASSY SUMMER TAFFY,2023-07-31,185.0,60.0,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,False,3.0,NaN,NaN,False,cohortes_sin_curva
2,GAITANA,ACHILLEA,LIGHT PINK,SASSY SUMMER TAFFY,2023-08-07,180.0,185.0,60.0,NaN,NaN,...,1.0,NaN,NaN,NaN,False,3.0,NaN,NaN,False,cohortes_sin_curva
3,GAITANA,ACHILLEA,LIGHT PINK,SASSY SUMMER TAFFY,2023-08-14,120.0,180.0,185.0,136.25,NaN,...,1.0,NaN,NaN,NaN,False,3.0,NaN,NaN,False,cohortes_sin_curva
4,GAITANA,ACHILLEA,LIGHT PINK,SASSY SUMMER TAFFY,2023-08-21,NaN,120.0,180.0,NaN,NaN,...,1.0,NaN,NaN,NaN,False,3.0,NaN,NaN,False,cohortes_sin_curva


## ¿Qué significa cada registro?

Cada fila es **una oportunidad de pronóstico semanal** para una combinación de **finca + producto + color + variedad**, emitida en una fecha (`origen`) y para un horizonte (`horizonte`). No representa una flor, un corte diario ni una siembra individual.

La semana empieza el lunes. **H1** corresponde a la propia semana del origen; **H5**, a la que empieza cuatro semanas después. Las variables históricas utilizan semanas anteriores al origen. `y` guarda la producción real de la semana objetivo para comparar posteriormente: **no es el pronóstico ni un dato disponible anticipadamente**.

Una misma semana de producción puede aparecer en varios registros porque se pronosticó desde diferentes orígenes y horizontes. Por eso **no se debe sumar `y` de toda la tabla como si fueran producciones distintas**.

### Ejemplo real de la cola de 2026: miniclavel

Para que podamos comparar con lo ocurrido, tomamos el último registro **en el orden del archivo** de MINICARNATION con origen en 2026, historial admisible y producción real reportada. No es necesariamente el origen más reciente: las filas finales sin producción real se excluyen de este ejemplo.


In [2]:
# Última fila de miniclavel de 2026 con historial admisible y resultado real.
ejemplo_2026 = base_analitica.loc[
    base_analitica["producto"].eq("MINICARNATION")
    & base_analitica["origen"].dt.year.eq(2026)
    & base_analitica["admisible_modelo"].eq(True)
    & base_analitica["y"].notna()
].tail(1)

if ejemplo_2026.empty:
    raise ValueError("No hay registros de miniclavel de 2026 que cumplan estas condiciones.")

# Una columna con todos los valores para leer el registro completo.
display(ejemplo_2026.T.rename(columns={ejemplo_2026.index[0]: "Valor del registro"}))

,Valor del registro
finca,GAITANA
producto,MINICARNATION
color,YELLOW
variedad,DINO
origen,2026-08-03 00:00:00
produccion_lag1,19202.0
produccion_lag2,20674.0
produccion_lag3,22469.0
media_4,22250.75
media_8,22893.75


### Ese registro, en palabras naturales

“Al comenzar el **3 de agosto de 2026**, queremos estimar cuántos tallos de **miniclavel DINO, amarillo, de GAITANA**, se producirán durante la semana del **31 de agosto al 6 de septiembre**. Es **H5**, porque contamos la semana del 3 de agosto como H1.”

- **Lo que ya sabíamos:** la última semana histórica empieza el **27 de julio** y tuvo **19.202 tallos**. El promedio de cuatro semanas era **22.250,75 tallos** y el de ocho, **22.893,75**. La diferencia de **−643 tallos** indica un nivel reciente menor; además, la última semana cayó **1.472 tallos** respecto a la anterior. Hay **213 semanas** históricas reportadas.
- **Lo que decía la proyección teórica:** sumaba **27.916,61 tallos**, pero **2 de las 25 cohortes no tenían cobertura válida**. Por eso `curva_completa` es falso, `motivo_cobertura` es `cohortes_sin_curva` y `teoria_modelo` está vacío. Esa suma parcial no se debe interpretar como una teoría completa ni como el pronóstico final.
- **Por qué la fila sigue siendo admisible:** tiene suficiente historia y un promedio reciente válido. El modelo puede utilizar la ruta de respaldo basada en producción reciente y su ajuste; el promedio de cuatro semanas tampoco es, por sí solo, su predicción final.
- **Lo que ocurrió después:** se reportaron **18.970 tallos reales** para la semana objetivo (`y`). Ese resultado sirve para evaluar la predicción una vez termina la semana.

Estos valores corresponden a la base cargada al preparar esta explicación. La celda anterior permite volver a consultar el registro completo.


## Mini diccionario de la base analítica

Se agrupan columnas relacionadas para cubrir las **47 columnas** sin repetir explicaciones.

| Columna(s) | Significado |
|---|---|
| `finca`, `producto`, `color`, `variedad` | Identifican la serie comercial: finca, producto, color y variedad cuya producción semanal se estudia. |
| `origen` | Lunes desde el que se emite el pronóstico; separa el pasado disponible del futuro por estimar. |
| `horizonte` | Horizonte del MODELO semanal: H1 es la semana del origen y H5 empieza cuatro semanas después. El modelo evalúa H1–H5, pero las proyecciones TEÓRICAS de cada plano abarcan 10 semanas y se cuentan desde la semana siguiente a fecha_plano. Son numeraciones distintas porque parten de fechas distintas. |
| `semana_objetivo` | Lunes de la semana que se pronostica; la semana abarca de lunes a domingo. |
| `ultima_semana_utilizada` | Lunes de la última semana de producción histórica utilizada, anterior al origen. |
| `y` | Producción real reportada de la semana objetivo, en tallos. Es la respuesta que se intenta predecir, no una variable que se pueda conocer anticipadamente. |
| `produccion_lag1`, `produccion_lag2`, `produccion_lag3` | Producción real, en tallos, de una, dos y tres semanas calendario antes del origen, respectivamente. |
| `media_4`, `media_8` | Promedio semanal de tallos durante las cuatro u ocho semanas anteriores al origen; requiere las cuatro u ocho observaciones. |
| `desv_4` | Desviación estándar de las cuatro semanas previas, en tallos: resume cuánto varió la producción reciente. |
| `tendencia_4_8` | media_4 menos media_8, en tallos. Un valor negativo indica un nivel reciente inferior al promedio de ocho semanas. |
| `cambio_reciente` | produccion_lag1 menos produccion_lag2, en tallos: cambio entre las dos últimas semanas. |
| `observaciones_previas` | Número de semanas históricas con producción reportada antes del origen; no tienen que ser consecutivas. |
| `temperatura_semana_lag1`, `humedad_semana_lag1`, `radiacion_semana_lag1` | Promedio climático de la semana anterior al origen, construido con los promedios diarios válidos. Una semana requiere al menos cinco días válidos. Conservan las unidades de la fuente depurada. |
| `temperatura_semana_media4`, `humedad_semana_media4`, `radiacion_semana_media4` | Promedio de los cuatro valores semanales anteriores de cada variable climática; requiere las cuatro semanas. El clima corresponde a la finca, no a una medición por variedad. |
| `fecha_estacional` | Fecha de la semana objetivo menos 52 semanas (364 días). |
| `produccion_52` | Producción real de la misma serie comercial en fecha_estacional, en tallos; referencia estacional del año anterior. |
| `semana_seno`, `semana_coseno` | Dos números que ubican la semana objetivo en un calendario circular: seno indica posición horizontal y coseno posición vertical (imaginando una aguja que parte de arriba y gira como un reloj). Se calculan a partir del número de semana del año; no son tallos ni porcentajes de producción. Para la semana 36 del ejemplo de DINO valen −0,935 y −0,355. Debajo de esta tabla se muestra el cálculo completo, paso a paso. |
| `union_finca`, `union_producto`, `union_color`, `union_variedad` | Nombres normalizados para unir la producción con las proyecciones. No son identificadores oficiales ni cultivos adicionales. |
| `plano` | Archivo o versión del plano del que procede la proyección seleccionada para ese origen. |
| `fecha_plano` | Fecha nominal de esa versión del plano. |
| `disponible` | Fecha supuesta de disponibilidad usada por el proceso para permitir utilizar ese plano. No certifica su publicación histórica real. |
| `teoria` | Producción teórica, en tallos, para la semana_objetivo de esta fila y la misma finca, producto, color y variedad, tomada del plano seleccionado. Se une por la fecha objetivo, no por igualdad del número de horizonte. No acumula H1–H5. En DINO, la semana del 31 de agosto al 6 de septiembre de 2026 es H5 del modelo emitido el 3 de agosto, pero horizonte teórico 7 del plano del 13 de julio: teoria = 27.916,61 tallos. Puede ser parcial si faltan grupos por cubrir; no es el pronóstico final del modelo. |
| `cohortes` | Número de grupos de plantas con la misma finca, producto, color, variedad, clave de curva y fecha de siembra dentro del plano. Un grupo puede reunir varias camas; no equivale a una cama física ni cuenta tallos. |
| `sin_cobertura` | Cantidad de cohortes sin cobertura válida de proyección; los estados proyectada y siembra_posterior no cuentan como faltantes. |
| `curva_completa` | Verdadero cuando existe teoría y sin_cobertura es cero; indica cobertura completa de esa proyección. |
| `teoria_modelo` | Valor de teoria habilitado como base teórica: se conserva si curva_completa es verdadero y queda vacío si la proyección es parcial. No es la predicción final del modelo. En DINO está vacío porque hay dos grupos sin cobertura. |
| `teoria_previa_1`, `teoria_previa_2` | Teorías de una y dos versiones anteriores del plano para la MISMA semana_objetivo y serie comercial. El 1 y el 2 cuentan versiones hacia atrás, no H1 y H2. Pueden existir incluso en H5 del modelo porque cada plano tiene 10 semanas teóricas. En DINO corresponden a los horizontes teóricos 8 y 9 de los planos anteriores. Aunque existían sus sumas parciales, ambas columnas están vacías porque solo conservan teorías anteriores con cobertura completa. También pueden faltar si no existe una versión previa que alcance esa semana objetivo; no se busca otra versión más antigua para reemplazar una incompleta. |
| `revision_teoria` | Cambio en tallos entre la teoría completa del plano seleccionado y teoria_previa_1, siempre para la misma semana objetivo. Positivo: la nueva versión proyecta más; negativo: menos. Si alguna de las dos proyecciones no es utilizable, queda vacío. No compara H5 contra H1. |
| `antiguedad_curva` | Tiempo en semanas entre origen y fecha_plano: indica qué tan antiguo es el plano seleccionado al emitir el pronóstico. No es la edad de las plantas. En DINO: del 13 de julio al 3 de agosto = 3 semanas. |
| `desviacion_reciente_teoria` | media_4 menos teoria_modelo, en tallos. Compara el promedio real de las cuatro semanas anteriores al origen con la teoría de la semana objetivo. No es un error de pronóstico porque compara períodos distintos. En DINO está vacío porque teoria_modelo está vacío. |
| `admisible_modelo` | Indica si la fila tiene media_4 y al menos 26 semanas históricas con producción reportada. No exige teoría completa ni y conocido, y no indica train o test. En DINO es verdadero por su historial, aunque la teoría no esté habilitada. |
| `motivo_cobertura` | Explica la cobertura teórica: curva_completa = proyección cubierta; cohortes_sin_curva = quedan grupos sin cobertura válida; sin_snapshot_disponible = no hay plano elegible; sin_pareja_comercial_u_objetivo = no coincide la serie o la semana objetivo. En DINO, cohortes_sin_curva corresponde a edades 9 y 16 sin valor en la curva utilizada; la etiqueta no demuestra que falte toda la curva de la variedad. |

### Teoría previa: versiones anteriores, no horizontes anteriores

**Hay dos preguntas distintas:** el horizonte dice **para qué semana** pronosticamos; `teoria_previa_1` y `teoria_previa_2` dicen **qué proyectaban versiones anteriores del plano para esa misma semana**. El 1 y el 2 cuentan versiones hacia atrás, no semanas objetivo H1 y H2.

Para el registro de DINO, mantenemos fija la semana del **31 de agosto al 6 de septiembre de 2026**. Al emitir el pronóstico el **3 de agosto**, el proceso seleccionó el plano de la semana 29. Al mirar las dos versiones anteriores, encontramos lo siguiente:

| Papel en esta fila | Plano | Disponibilidad usada por el proceso | Teoría calculada para el 31 de agosto–6 de septiembre | Grupos sin cobertura | Valor que se habilita |
|---|---|---|---:|---:|---|
| Teoría del plano seleccionado | Semana 29 | 28 de julio | 27.916,61 tallos | 2 | `teoria` conserva la suma parcial; `teoria_modelo` queda vacío. |
| Una versión atrás | Semana 28 | 21 de julio | 29.979,80 tallos | 2 | `teoria_previa_1` queda vacío. |
| Dos versiones atrás | Semana 27 | 14 de julio | 31.268,38 tallos | 2 | `teoria_previa_2` queda vacío. |

**No confundir los dos alcances:** el modelo semanal evalúa H1–H5 desde su fecha de origen, pero las proyecciones teóricas guardadas abarcan **10 semanas por plano** (`HORIZONTE = 10`). Además, el generador teórico cuenta desde la semana siguiente a `fecha_plano`, mientras el modelo cuenta H1 como la propia semana de `origen`. Por eso sus números de horizonte no se pueden intercambiar directamente.

En este ejemplo, el 31 de agosto es **H5 para el modelo emitido el 3 de agosto**, pero es el horizonte teórico **7 del plano del 13 de julio**, **8 del plano del 6 de julio** y **9 del plano del 29 de junio**. Los tres existen dentro de las diez semanas generadas. Las teorías previas están vacías por cobertura incompleta, no porque se haya superado un límite de cinco semanas. Si un plano anterior no alcanzara la semana objetivo, tampoco habría una teoría previa disponible para esa semana.

**Aquí sí existían proyecciones anteriores.** Las columnas previas están vacías porque el código conserva únicamente valores anteriores con cobertura completa. En cambio, `teoria` conserva también la suma parcial del plano seleccionado. Esa diferencia explica por qué podemos ver un número en `teoria` y vacíos en las dos columnas previas.

En otros registros, una teoría previa también puede faltar porque no exista esa versión anterior para la serie y semana objetivo. El cálculo toma las versiones anteriores en orden de disponibilidad; **no salta una versión incompleta para buscar otra completa más antigua**. Tampoco tienen que estar separadas exactamente por una semana.

**Ejemplo inventado con cobertura completa:** si el plano seleccionado proyecta 28.000 tallos, la versión anterior proyectaba 30.000 y la anterior a esa 31.000, entonces `teoria_modelo = 28.000`, `teoria_previa_1 = 30.000`, `teoria_previa_2 = 31.000` y `revision_teoria = 28.000 − 30.000 = −2.000 tallos`. Significa que la proyección para **la misma semana** se revisó a la baja en 2.000 tallos. No significa que la producción real haya caído esa cantidad.

En el registro real de DINO, `revision_teoria` y `desviacion_reciente_teoria` están vacíos porque requieren teoría habilitada. La fila sigue siendo admisible por su historial de producción; eso no convierte la suma parcial en una teoría completa.

### Seno y coseno: cómo se calculan y qué significan

**Estas dos columnas son una forma de escribir la fecha para que el modelo entienda en qué época del año estamos. No calculan producción.** Se obtienen de la **semana objetivo**, no de la semana de origen ni del horizonte H1–H5.

#### 1. Primero sacamos el número de semana del año

En el ejemplo de DINO queremos pronosticar la semana que empieza el **31 de agosto de 2026**. Esa fecha pertenece a la **semana 36 del año**, según el calendario ISO (semanas que empiezan el lunes).

Aquí tenemos dos números distintos: **H5** significa que estamos pronosticando la quinta semana contando desde el origen; **36** es la posición de la semana objetivo dentro del año. Para calcular seno y coseno utilizamos **36**, no 5.

#### 2. Convertimos esa semana en una posición alrededor de un círculo

Piensa en un reloj: después de dar una vuelta, volvemos al comienzo. El calendario también vuelve a empezar después de diciembre.

Dividimos el círculo en **52 pasos**, uno por semana. Para ubicar la semana 36:

- Dividimos **36 / 52 = 0,6923**. Eso equivale al **69,23 % de una vuelta** en esta representación del calendario; no es un porcentaje de producción ni una medida exacta de los días transcurridos del año.
- Una vuelta tiene **360 grados**, así que hacemos **0,6923 × 360 = 249,23 grados**.
- Imagina una aguja que sale del centro: empieza apuntando hacia arriba y gira en sentido horario hasta esa posición. Para la semana 36 termina apuntando hacia abajo y a la izquierda.

#### 3. Seno y coseno describen dónde termina la aguja

Si la aguja mide una unidad, podemos describir su punta con dos números:

- **`semana_seno`: posición horizontal.** Derecha es positiva; izquierda es negativa.
- **`semana_coseno`: posición vertical.** Arriba es positiva; abajo es negativa.

Las funciones matemáticas *seno* y *coseno* hacen esa conversión del ángulo a las dos posiciones. Python las calcula automáticamente; no hay que inventarlas ni estimarlas con datos de producción.

```text
                           ARRIBA
                         semana 52
                       seno=0, cos=1
                              |
     IZQUIERDA ---------------+--------------- DERECHA
     semana 39                |                semana 13
     seno=-1, cos=0           |                seno=1, cos=0
                            ABAJO
                          semana 26
                        seno=0, cos=-1
```

**Para la semana 36**, los resultados son:

| Columna | Cálculo con el ángulo en grados | Resultado aproximado | Significado |
|---|---|---:|---|
| `semana_seno` | seno de 249,23° | −0,935 | La punta está hacia la izquierda del centro. |
| `semana_coseno` | coseno de 249,23° | −0,355 | La punta está un poco por debajo del centro. |

**No leas −0,935 como −93,5 % de producción.** Ambos números solo indican posición en el calendario. Tampoco significan que la producción vaya a bajar.

#### 4. Así se hace en Python

Python utiliza **radianes** para los ángulos: es otra unidad, igual que medir una distancia en metros o centímetros. **360 grados equivalen a 2 × π radianes**, con π aproximadamente igual a 3,1416. Por eso el cálculo del notebook es:

```python
import numpy as np
import pandas as pd

fecha_objetivo = pd.Timestamp("2026-08-31")
semana_del_anio = fecha_objetivo.isocalendar().week  # 36, no H5
angulo = 2 * np.pi * semana_del_anio / 52           # 4,3499 radianes = 249,23°

semana_seno = np.sin(angulo)      # aproximadamente -0,935
semana_coseno = np.cos(angulo)    # aproximadamente -0,355
```

Este bloque ilustra el cálculo; esas columnas ya vienen calculadas en el parquet.

#### 5. ¿Por qué usamos los dos números y para qué sirven?

**Para conservar la cercanía entre diciembre y enero.** Si usamos únicamente el número de semana, 52 y 1 parecen estar muy lejos. En el círculo, la semana 52 tiene valores **(0; 1)** y la semana 1 tiene **(0,121; 0,993)**: quedan cerca, como sucede en el calendario.

**Usamos ambos porque uno solo puede ser ambiguo.** Por ejemplo, las semanas 13 y 39 tienen el mismo coseno (0), pero están en épocas diferentes. El seno permite distinguirlas: en una vale 1 y en la otra −1.

El modelo recibe esos dos números junto con los demás insumos y puede aprender si hay diferencias recurrentes de producción según la época del año. **Estas columnas no dicen por sí solas cuánto se producirá ni garantizan una mejora del modelo.** Solo aportan información del calendario, sin consultar clima ni producción futura.

*Detalle del cálculo actual:* se utiliza un ciclo fijo de 52 semanas. Algunos años ISO tienen semana 53; con esta fórmula recibe la misma posición que la semana 1. Es una aproximación del calendario anual.

**Cómo interpretar los vacíos:** `NaN`, `NaT` o `<NA>` significan dato ausente o no utilizable, no cero. Por ejemplo, que falte una teoría previa no significa que esa versión pronosticara cero tallos.

**Alcance de esta tabla:** es la base semanal común. Los notebooks posteriores añaden variables específicas, como tendencias de corte diario. Que una columna esté aquí no significa que todos los modelos la utilicen. Tampoco están aquí el pronóstico final del modelo ni el estimado del ingeniero: para comparar errores hay que consultar las salidas de predicción correspondientes. La división entre entrenamiento y prueba se aplica después, por fechas.